name: publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v1
      - uses: actions/checkout@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
      - name: Set up secret file
          env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: bun i
      - run: bun run build
      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
          npm publish